name: rag-case-study-v3
services:
- name: rag-case-study-v3
  github:
    branch: main
    repo: SuShiva/rag-case-study-v3
  build_command: pip install -r requirements.txt
  run_command: bash startup.sh
  http_port: 8501
  source_dir: .
  envs:
  - key: PINECONE_API_KEY
    scope: RUN_TIME
    value: ${PINECONE_API_KEY}
